version: "3.7"

services:
  db:
    image: postgres:12.2
    container_name: lunch-time-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "defaultpassword"

  client:
    build:
      context: ./client/
    container_name: lunch-time-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
